/**
 * Every concrete /api route must have a public MCP operation or an explicit
 * browser-session boundary. Keep this map keyed by Hono's registered method and
 * path so adding a route cannot silently bypass the parity review.
 */
export const apiParity = {
  "GET /api/dashboard": ["get_dashboard", "review_overdue_events"],
  "GET /api/dashboard/events": ["get_dashboard"],
  "GET /api/dashboard/explain": ["explain_forecast"],
  "POST /api/dashboard/simulate": ["simulate_forecast"],
  "POST /api/dashboard/confirm": ["confirm_forecast"],
  "GET /api/accounts": ["list_accounts"],
  "POST /api/accounts": ["create_account"],
  "PUT /api/accounts/:id": ["update_account"],
  "POST /api/accounts/:id/reconcile": ["reconcile_account"],
  "DELETE /api/accounts/:id": ["delete_account"],
  "GET /api/transactions": ["list_transactions"],
  "GET /api/transactions/balance-history": ["get_balance_history"],
  "POST /api/transactions": ["create_transaction"],
  "PUT /api/transactions/:id": ["update_transaction"],
  "DELETE /api/transactions/:id": ["delete_transaction"],
  "GET /api/salary-records": ["list_salary_records"],
  "GET /api/salary-records/:id": ["get_salary_record"],
  "POST /api/salary-records": ["create_salary_record"],
  "PATCH /api/salary-records/:id": ["update_salary_record"],
  "DELETE /api/salary-records/:id": ["delete_salary_record"],
  "GET /api/donations": ["list_donations"],
  "POST /api/donations": ["create_donation"],
  "PATCH /api/donations/:id": ["update_donation"],
  "DELETE /api/donations/:id": ["delete_donation"],
  "GET /api/furusato/simulation": ["get_furusato_simulation"],
  "PUT /api/furusato/simulation-input": ["save_furusato_simulation_input"],
  "GET /api/recurring-items": ["list_recurring_items"],
  "GET /api/recurring-items/:id": ["get_recurring_item"],
  "POST /api/recurring-items": ["create_recurring_item"],
  "PUT /api/recurring-items/:id": ["update_recurring_item"],
  "DELETE /api/recurring-items/:id": ["delete_recurring_item"],
  "GET /api/recurring-items/:id/amount-changes": ["list_recurring_item_amount_changes"],
  "POST /api/recurring-items/:id/amount-changes": ["create_recurring_item_amount_change"],
  "PUT /api/recurring-items/:id/amount-changes/:changeId": ["update_recurring_item_amount_change"],
  "DELETE /api/recurring-items/:id/amount-changes/:changeId": ["delete_recurring_item_amount_change"],
  "GET /api/subscriptions": ["list_subscriptions"],
  "GET /api/subscriptions/:id": ["get_subscription"],
  "GET /api/subscriptions/monthly/:yearMonth": ["get_subscription_monthly"],
  "POST /api/subscriptions": ["create_subscription"],
  "PUT /api/subscriptions/:id": ["update_subscription"],
  "DELETE /api/subscriptions/:id": ["delete_subscription"],
  "GET /api/subscriptions/:id/amount-changes": ["list_subscription_amount_changes"],
  "POST /api/subscriptions/:id/amount-changes": ["create_subscription_amount_change"],
  "PUT /api/subscriptions/:id/amount-changes/:changeId": ["update_subscription_amount_change"],
  "DELETE /api/subscriptions/:id/amount-changes/:changeId": ["delete_subscription_amount_change"],
  "GET /api/credit-cards": ["list_credit_cards"],
  "GET /api/credit-cards/:id/assumption-suggestion": ["get_credit_card_assumption_suggestion"],
  "POST /api/credit-cards": ["create_credit_card"],
  "PUT /api/credit-cards/:id": ["update_credit_card"],
  "DELETE /api/credit-cards/:id": ["delete_credit_card"],
  "GET /api/billings": ["get_billing"],
  "PUT /api/billings/:yearMonth": ["update_billing"],
  "GET /api/loans": ["list_loans"],
  "POST /api/loans": ["create_loan"],
  "PUT /api/loans/:id": ["update_loan"],
  "DELETE /api/loans/:id": ["delete_loan"],
  "GET /api/people": ["list_people"],
  "POST /api/people": ["create_person"],
  "PUT /api/people/:id": ["update_person"],
  "DELETE /api/people/:id": ["delete_person"],
  "GET /api/people/:id/summary": ["get_person_summary"],
  "GET /api/splits": ["list_splits"],
  "POST /api/splits": ["set_transaction_split"],
  "GET /api/splits/:id": ["get_split"],
  "PUT /api/splits/:id": ["set_transaction_split"],
  "DELETE /api/splits/:id": ["delete_split"],
  "GET /api/settlements": ["list_settlements"],
  "POST /api/settlements": ["create_settlement"],
  "DELETE /api/settlements/:id": ["delete_settlement"],
  "GET /api/auth/status": { browserSession: "Login state belongs to the browser session" },
  "GET /api/auth/login": { browserSession: "OIDC state, PKCE and callback cookies are browser-bound" },
  "GET /api/auth/callback": { browserSession: "OIDC callback consumes browser-bound flow cookies" },
  "POST /api/auth/logout": { browserSession: "Revokes the current browser cookie session" },
  "GET /api/auth/tokens": { browserSession: "Requires an OIDC browser session" },
  "POST /api/auth/tokens": { browserSession: "Requires an OIDC browser session to mint a credential" },
  "DELETE /api/auth/tokens/:id": { browserSession: "Requires an OIDC browser session to revoke a credential" },
  "GET /api/auth/sessions": { browserSession: "Lists the current OIDC subject's browser sessions" },
  "DELETE /api/auth/sessions": { browserSession: "Revokes the current OIDC subject's browser sessions" },
  "DELETE /api/auth/sessions/:id": { browserSession: "Revokes the current OIDC subject's browser session" },
  "GET /api/audit-logs": ["list_recent_changes"],
  "GET /api/settings": ["get_ui_settings"],
  "PUT /api/settings": ["update_ui_settings"],
  "GET /api/export": ["export_data"],
  "POST /api/import": ["import_data"],
  "GET /api/spending": ["get_spending"],
  "POST /api/spending/commands": ["update_spending"],
  "POST /api/spending/imports/preview": ["preview_spending_import"],
  "POST /api/spending/:id/review": ["review_spending"],
  "POST /api/spending/:id/override": ["override_spending"],
  "GET /api/spending/ai/status": { browserSession: "AI connection configuration is managed in the UI" },
  "POST /api/spending/ai/config": { browserSession: "AI connection and credentials are managed in the UI" },
  "POST /api/spending/ai/models": { browserSession: "AI connection inspection is managed in the UI" },
  "POST /api/spending/ai/test": { browserSession: "AI connection inspection is managed in the UI" },
} as const satisfies Record<string, readonly string[] | { readonly browserSession: string }>;
