ALTER TABLE "accounts"
  ADD COLUMN "currency_code" VARCHAR(3) NOT NULL DEFAULT 'JPY',
  ADD COLUMN "exchange_rate_to_jpy" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN "exchange_rate_updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
